version: '3.5'

services:
  freegpt-webui:
    restart: always
    container_name: freegpt-webui-x
    build:
      context: .
      dockerfile: Dockerfile
      #dockerfile: Dockerfile-ubuntu
    ports:
      - "1338:1338"
    volumes:
      - ../GPT4All-models:/app/gpt4all
      #- ./gpt4all:/app/gpt4all
      - ./config.json:/app/config.json