version: '3.5'

services:
  freegpt-webui:
    restart: always
    container_name: freegpt-webui-x
    image: yinghk/freegpt-webui-x:latest
    ports:
      - "1338:1338"
    volumes:
      - ../GPT4All-models:/app/gpt4all
      - ./config-docker.json:/app/config.json
      - ./logs:/app/logs